### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by minkoonim** [app-generator/django-volt-dashboard-pro#1]
```
     Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-req-build-i4n8ogs5\setup.py", line 5, in <module>
          README = readme.read()
                   ^^^^^^^^^^^^^
      UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 367: illegal multibyte sequence
```

pip & poetry on windows result in this error.
linux works though.

**Comment by app-generator** [comment]
Hello @minkoonim 

Can you tell us more about your environment? 

All apps are cross-tested using Python 3.10/PIP on: 

- Window11
- Ubuntu 18.04
- LIVE Deploy on Render 

Regarding your error, seems to bump quite early because the Django Codebase is not yet hit. 
Anyway, we will take a look and get back with some input. 

In all cases, let us know your progress. 
Ty!

**Comment by app-generator** [comment]
P.S. @minkoonim 

The solution suggested on this link, might help:

https://groups.google.com/g/django-developers/c/ZkmnmGz_W58

`set the PYTHONIOENCODING to utf8 before launching Python`
